### PR TITLE
Compressed all the images

### PR DESCRIPTION
**Pull request by RishiTheGoat**

### CODE REVIEW

**Review by matthijs186 — APPROVED** [review]
All clean.

**Review by ferrybig — CHANGES_REQUESTED** [review]
Wrong directory for images

**Review by Drelofs — APPROVED** [review]
Pictures are smaller in size and still look good! You can merge it!

**Review by matthijs186 — CHANGES_REQUESTED** [review]
Woops, I missed that one @ferrybig.

**Pull request closed without merging**
