### PR TITLE
Added metadata to index.html

### PR DESCRIPTION
**Pull request by Drelofs**
Added metadata tags for charset, description, viewport and author

### CODE REVIEW

**Review by peterxqe — COMMENTED** [review]
competa both uppercase

**Comment by matthijs186** [comment]
Looks good to me.

**Comment by Drelofs** [comment]
Applied change in metadata

**Review by matthijs186 — APPROVED** [review]
It's weird that this comes from `feature/footer` though, but it should be OK.

**Comment by matthijs186** [comment]
We'll look at this again later

**Pull request closed without merging**
